In [1]:
# %%
import cupy as cp
from matplotlib import pyplot as plt
import time


# %%
class PSNR: 
    def __init__(self,clean,dirty,mask,device):
        self.init_device(device)
        self.get = self.get_psnr(clean ,dirty,mask) #. squeeze(),dirty.squeeze())
  
    def init_device(self,device):
         cp.cuda.Device(device).use()
            
 
    def get_values(self,image,mask): 
        mask = mask[0]
        values = []
        mask = mask[1:len(mask)]
       
        for point in mask:
            idx = point[0].numpy()
            idy = point[1].numpy()
            values.append(image[idx][idy])
        values = cp.array(values)
        print('values dirty:'+str(values))
        return values
    

    def get_psnr(self,clean,dirty,mask):
        clean = clean.squeeze()
        print(clean)
        clean = cp.array(clean)
        dirty = dirty.squeeze() 
        print(dirty)
        dirty = cp.array(dirty)
        values = self.get_values(dirty,mask)  
        idx = mask[0][0][0].numpy()
        idy = mask[0][0][1].numpy()
        max_value = cp.max(dirty)
        print('max value dirty:' + str(max_value))
        print('max value dirty:' + str(max_value))
        std_value = cp.std(values)
        print('std value dirty:' + str(std_value))
        psnr = cp.asnumpy((20*cp.log10(max_value/std_value))).item(0) 
        print('psnr dirty:' + str(psnr))
        return psnr
     

In [8]:
from datasetInterferometry import DatasetInterferometry
from simulator import Simulator

size_figure = 640
Simulator.create_save(size = size_figure,start = 0,stop = 5,step = 1, device = 0)
type_psf = 'psf_real_'+str(size_figure)+'x'+str(size_figure)
batch_train = 1
device = 0

data = DatasetInterferometry(size_figure = size_figure,
                                     type_psf = type_psf,
                                     batch_train = batch_train,
                                     device = device)
testloader = data.read_test_data(0,10)
data.view_data(testloader)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ...

KeyboardInterrupt: 

In [ ]:
from tqdm import tqdm

for dirty,clean,mask in tqdm((testloader)):
            #print(mask)
            psnr= PSNR(clean,dirty,mask,device).get
        